application: species-explorer
version: 1
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "30d"

builtins:
- deferred: on

handlers:
- url: /css
  static_dir: css

- url: /data
  static_dir: data

- url: /image
  static_dir: image

- url: /js
  static_dir: js

- url: /semantic
  static_dir: semantic

- url: /.*
  script: speciesexplorer.application
